// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGEdSl5xFhESr1v72M77K8sTk5cy0n85c',
    appId: '1:664081203712:web:f92d34614e4e76efb28ee5',
    messagingSenderId: '664081203712',
    projectId: 'ecommerce-add12',
    authDomain: 'ecommerce-add12.firebaseapp.com',
    storageBucket: 'ecommerce-add12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLHJX1iByVIq28AO-VivVMY4h0-Q1WFoo',
    appId: '1:664081203712:android:0d18224c4919cf7eb28ee5',
    messagingSenderId: '664081203712',
    projectId: 'ecommerce-add12',
    storageBucket: 'ecommerce-add12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB5H1oSyK6aBhpOm_kH1N62QhUcGkcZKU',
    appId: '1:664081203712:ios:af026ce342d48c43b28ee5',
    messagingSenderId: '664081203712',
    projectId: 'ecommerce-add12',
    storageBucket: 'ecommerce-add12.appspot.com',
    iosBundleId: 'com.laith.ecommerce',
  );
}
